  <section id="content_in">
    
     <?php
                    
                    if(isset($this->messageError)){
                     ?>
                     <h3 style="color: #ba1616;" class="msn_error">
                     <?php  
                     echo $this->messageError;
                     ?>
                     </h3>
                     <?php   
                    }
                    
                    ?>
                    
                     <?php
                    
                    if(isset($this->messageOk)){
                     ?>
                     <h3 style="color: green;" class="msn_ok">
                     <?php  
                     echo $this->messageOk;
                     ?>
                     </h3>
                     <?php   
                    }
                    
                    ?>
  
    <fieldset>
        
                     
        
     <form action="" method="post" name="form_update" id="form_update">
     <legend></legend>
        <label>Password:</label>
        <input type="password" name="pass" id="pass" />
        <label>Repetir Password:</label>
        <input type="password" name="rpass" id="rpass" />
        <input type="hidden" name="valid" value="ok" />
        <div class="msn_resp"></div>
        <input type="button" title="Cambiar Password" value="Cambiar Password" id="btn" onclick="javascript:change_pass('<?php echo BASE_URL ?>','<?php echo DEFAULT_LAYOUT ?>');" />
        
        
     </form>   
    </fieldset>
    
    
    <fieldset>
        
                  
     <form action="" method="post" name="form_update_data" id="form_update_data">
        <label>Nombres:</label>
        <input type="text" name="name" value="<?php if(isset($_POST["name"])): echo $_POST["name"]; else: echo $this->user[0]["nombres"]; endif; ?>" />
        <label>Apellidos:</label>
        <input type="text" name="apelli" value="<?php if(isset($_POST["apelli"])): echo $_POST["apelli"]; else:  echo $this->user[0]["apellidos"]; endif; ?>" />
        <label>Telefono:</label>
        <input type="text" name="tel" value="<?php if(isset($_POST["tel"])): echo $_POST["tel"]; else: echo $this->user[0]["telefono"]; endif; ?>" />
        <label>Email:</label>
        <input type="text" name="email"  value="<?php if(isset($_POST["email"])): echo $_POST["email"]; else: echo $this->user[0]["email"]; endif; ?>"/>
        <input type="hidden" name="valid2" value="ok" />
        <div class="msn_resp"></div>
        <input type="button" title="Cambiar Datos" value="Cambiar Datos" id="btn" onclick="javascript:change_data('<?php echo BASE_URL ?>','<?php echo DEFAULT_LAYOUT ?>');" />
        
        
     </form>   
    </fieldset>
  
  </section>