            
            
            <section id="content_in">
            <h3 style="color: #ba1616;" class="msn_error">
                  <?php
                
                if(isset($this->messageError)){
                 ?>
                 <?php  
                 echo $this->messageError;
                 ?>
                 <?php   
                }
                
                ?>
                 </h3>
               <fieldset> 
               
               <form id="form_add" method="post" action="">

                    <legend></legend>
                    <input type="hidden" value="<?php echo $this->data[0]["id"] ?>" name="id" /> 
                    <label>Nombre campeonato:</label>
                    <input type="text" name="nombre_campeonato" value="<?php if(isset($_POST["nombre_campeonato"])): echo $_POST["nombre_campeonato"]; else: echo $this->data[0]["nombre_campeonato"]; endif; ?>" />
                    
                    
                    <label>Fecha Inicio</label>
                    <input type="text" name="fecha_inicio" class="datepicker" readonly="readOnly" value="<?php if(isset($_POST["fecha_inicio"])): echo $_POST["fecha_inicio"]; else: echo $this->data[0]["fecha_inicio"]; endif; ?>" />
                   
                    <label>Fecha Fin</label>
                   <input type="text" name="fecha_fin" class="datepicker" readonly="readOnly" value="<?php if(isset($_POST["fecha_fin"])): echo $_POST["fecha_fin"]; else: echo $this->data[0]["fecha_fin"]; endif; ?>"/>
                    
                    <input type="hidden" value="<?php echo $this->data[0]["estado"] ?>" name="estado" />
                                     
                    <input type="hidden" value="ok" name="valid" />
                    <label></label>
                    <input type="button" id="btn" value="Guardar" title="Guardar" onclick="javascript:form_add.submit();" />
                    
                
                </form>
               </fieldset>
               
                  
            </section>
            