    <section id="content_in">
    <?php
                    
                    if(isset($this->messageError)){
                     ?>
                     <h3 style="color: #ba1616;" class="msn_error">
                     <?php  
                     echo $this->messageError;
                     ?>
                     </h3>
                     <?php   
                    }
                    
                    ?>
                    
                     <?php
                    
                    if(isset($this->messageOk)){
                     ?>
                     <h3 style="color: green;" class="msn_ok">
                     <?php  
                     echo $this->messageOk;
                     ?>
                     </h3>
                     <?php   
                    }
                    
                    ?>    
    <fieldset>
                            
                <form name="add" action="" method="post" id="add">
                <legend></legend>
                <label>Editar Especialidad: </label>
                
                <input type="hidden" name="id" value="<?php echo $this->data[0]["id"]; ?>" />
                <input type="text" name="especialidad" value="<?php echo $this->data[0]["especialidad"]; ?>" />
                <input type="hidden" name="valid" value="ok" />
                <input type="button" value="Actualizar" id="btn" onclick="javascript:$('#add').submit();"/>
                </form>
                </fieldset>  
      </section>          