     
            
            <section id="content_in">
                <?php
                
                if(isset($this->message)){
                 ?>
                 <h2>
                 <?php  
                 echo $this->message;
                 ?>
                 </h2>
                 <?php   
                }
                
                ?>
                
                <?php 
                echo $this->html_helper->open_tag('center');
                echo $this->html_helper->open_tag('table',array("id"=>"table","class"=>"sortable"));
                  echo $this->html_helper->open_tag('thead');  
                    echo $this->html_helper->open_tag('tr',array("class"=>"tr_class"));
                     
                         echo $this->html_helper->open_tag('th',array("class"=>"tr_class"));
                            echo "Nombre Medico";
                         echo $this->html_helper->close_tag('th',array("class"=>"tr_class"));
                         
                         echo $this->html_helper->open_tag('th',array("class"=>"tr_class"));
                            echo "Nombre Paciente";
                         echo $this->html_helper->close_tag('th',array("class"=>"tr_class"));
                         
                         echo $this->html_helper->open_tag('th',array("class"=>"tr_class"));
                            echo "Hora Cita";
                         echo $this->html_helper->close_tag('th',array("class"=>"tr_class"));
                         
                         echo $this->html_helper->open_tag('th',array("class"=>"tr_class"));
                            echo "Estado Cita";
                         echo $this->html_helper->close_tag('th',array("class"=>"tr_class"));
                         
                         echo $this->html_helper->open_tag('th',array("class"=>"tr_class"));
                            echo "Fecha";
                         echo $this->html_helper->close_tag('th',array("class"=>"tr_class"));
                         
                         echo $this->html_helper->open_tag('th',array("class"=>"tr_class"));
                            echo "Editar";
                         echo $this->html_helper->close_tag('th',array("class"=>"tr_class"));
                         
                         echo $this->html_helper->open_tag('th',array("class"=>"tr_class"));
                            echo "Eliminar";
                         echo $this->html_helper->close_tag('th',array("class"=>"tr_class"));
                         
                      echo $this->html_helper->close_tag('tr',array("class"=>"tr_class"));
                   echo $this->html_helper->close_tag('thead');   
                   echo $this->html_helper->open_tag('tbody');
                if(isset($this->data) && count($this->data)): 
                  
                  
                  
                    foreach($this->data as $key=>$value):
                ?>
                
                <?php
                
                    
                     echo $this->html_helper->open_tag('tr',array("class"=>"tr_class"));
                     
                         echo $this->html_helper->open_tag('td',array("class"=>"tr_class"));
                            echo $this->methods->cutWord($value["nombre_medico"]. " " .$value["apellido_medico"],"25");
                         echo $this->html_helper->close_tag('td');
                         
                         echo $this->html_helper->open_tag('td',array("class"=>"tr_class"));
                            echo $this->methods->cutWord($value["nombre_paciente"]. " " .$value["apellido_paciente"],"25");
                         echo $this->html_helper->close_tag('td');
                         
                         echo $this->html_helper->open_tag('td',array("class"=>"tr_class"));
                            echo $this->methods->cutWord($value["hora_inicio"],"25");
                         echo $this->html_helper->close_tag('td');
                         
                         
                            
                            if($value["estado"]=="1"):
                            echo $this->html_helper->open_tag('td',array("class"=>"cita_esp"));
                            echo "En Espera";
                            echo $this->html_helper->close_tag('td');
                            else:
                                
                                if($value["estado"]=="2"):
                                echo $this->html_helper->open_tag('td',array("class"=>"cita_efect"));
                                  echo "Efectuado";
                                echo $this->html_helper->close_tag('td');
                                else:
                                    echo $this->html_helper->open_tag('td',array("class"=>"cita_cancel"));
                                    echo "Cancelado";
                                    echo $this->html_helper->close_tag('td');
                                endif;
                            endif;
                            
                            
                         
                         
                         echo $this->html_helper->open_tag('td',array("class"=>"tr_class"));
                            echo $value["fecha"];
                         echo $this->html_helper->close_tag('td');
                         
                         echo $this->html_helper->open_tag('td',array("class"=>"tr_class"));
                           
                            echo $this->html_helper->open_tag('a',array("href"=>BASE_URL . "citas/edit/".$value["id_visita"].".html"));
                            echo "Editar";
                            echo $this->html_helper->close_tag('a');
                            
                         echo $this->html_helper->close_tag('td',array("class"=>"tr_class"));
                         
                         echo $this->html_helper->open_tag('td',array("class"=>"tr_class"));
                           
                           echo $this->html_helper->open_tag('a',array("href"=>BASE_URL . "citas/delete/".$value["id_visita"].".html"));
                            echo "Eliminar";
                           echo $this->html_helper->close_tag('a'); 
                            
                         echo $this->html_helper->close_tag('td',array("class"=>"tr_class"));
                         
                      echo $this->html_helper->close_tag('tr');
                    
                    
                ?>    
                    
                
                <?php
                    endforeach;
                  
                  
                    
                endif; 
                echo $this->html_helper->close_tag('tbody');
                echo $this->html_helper->close_tag('table');
                ?>
                <div id="controls">
            		<div id="perpage">
            			<select onchange="sorter.size(this.value)">
            			<option value="5" >5</option>
            				<option value="10" selected="selected">10</option>
            				<option value="20">20</option>
            				<option value="50">50</option>
            				<option value="100">100</option>
            			</select>
            			<span>Registros Por Pagina</span>
            		</div>
            		<div id="navigation">
            			<img src="<?php echo $_layoutParams['ruta_img']; ?>first.gif" width="16" height="16" alt="First Page" onclick="sorter.move(-1,true)" />
            			<img src="<?php echo $_layoutParams['ruta_img']; ?>previous.gif" width="16" height="16" alt="First Page" onclick="sorter.move(-1)" />
            			<img src="<?php echo $_layoutParams['ruta_img']; ?>next.gif" width="16" height="16" alt="First Page" onclick="sorter.move(1)" />
            			<img src="<?php echo $_layoutParams['ruta_img']; ?>last.gif" width="16" height="16" alt="Last Page" onclick="sorter.move(1,true)" />
            		</div>
            		<div id="text">Vista Pagina <span id="currentpage"></span> de <span id="pagelimit"></span></div>
            	</div>
            	<script src="<?php echo $_layoutParams['ruta_js']; ?>script_table_sorter.js" type="text/javascript"></script>
            	<script type="text/javascript">
              var sorter = new TINY.table.sorter("sorter");
            	sorter.head = "head";
            	sorter.asc = "asc";
            	sorter.desc = "desc";
            	sorter.even = "evenrow";
            	sorter.odd = "oddrow";
            	sorter.evensel = "evenselected";
            	sorter.oddsel = "oddselected";
            	sorter.paginate = true;
            	sorter.currentid = "currentpage";
            	sorter.limitid = "pagelimit";
            	sorter.init("table",1);
              </script>
                <?php
                echo $this->html_helper->close_tag('center');
                ?>            
            
                       
            </section>
            
       
            