<section id="content_in">
                <?php
                    
                    if(isset($this->messageError)){
                     ?>
                     <h3 style="color: #ba1616;" class="msn_error">
                     <?php  
                     echo $this->messageError;
                     ?>
                     </h3>
                     <?php   
                    }
                    
                    ?>
                    
                     <?php
                    
                    if(isset($this->messageOk)){
                     ?>
                     <h3 style="color: green;" class="msn_ok">
                     <?php  
                     echo $this->messageOk;
                     ?>
                     </h3>
                     <?php   
                    }
                    
                    ?> 
                 <fieldset>
                               
                <form name="add" action="" method="post" id="add">
                <legend></legend>
                <label>Agregar Especialidad: </label>
                
                <input type="text" name="especialidad" />
                <input type="hidden" name="valid" value="ok" />
                <input type="button" value="Agregar" id="btn" onclick="javascript:$('#add').submit();"/>
                </form>
                </fieldset>  
                <?php 
                echo $this->html_helper->open_tag("center");
                echo $this->html_helper->open_tag('table',array("id"=>"table","class"=>"sortable"));
                  echo $this->html_helper->open_tag('thead');  
                    echo $this->html_helper->open_tag('tr',array("class"=>"tr_class"));
                     
                         echo $this->html_helper->open_tag('th',array("class"=>"tr_class"));
                            echo "Especialidad";
                         echo $this->html_helper->close_tag('th',array("class"=>"tr_class"));
                         
                         echo $this->html_helper->open_tag('th',array("class"=>"tr_class"));
                            echo "Editar";
                         echo $this->html_helper->close_tag('th',array("class"=>"tr_class"));
                         
                         echo $this->html_helper->open_tag('th',array("class"=>"tr_class"));
                            echo "Eliminar";
                         echo $this->html_helper->close_tag('th',array("class"=>"tr_class"));
                         
                      echo $this->html_helper->close_tag('tr',array("class"=>"tr_class"));
                    echo $this->html_helper->close_tag('thead');
                    
                  echo $this->html_helper->open_tag('tbody');      
                if(isset($this->data) && count($this->data)): 
                
                    foreach($this->data as $key=>$value):
                ?>
                
                <?php
                
                    
                     echo $this->html_helper->open_tag('tr',array("class"=>"tr_class"));
                     
                         echo $this->html_helper->open_tag('td',array("class"=>"tr_class"));
                            echo $value["especialidad"];
                         echo $this->html_helper->close_tag('td');
                         
                                                
                         echo $this->html_helper->open_tag('td',array("class"=>"tr_class"));
                           
                            echo $this->html_helper->open_tag('a',array("href"=>BASE_URL . "citas/edit_specialty/".$value["id"].".html"));
                            echo "Editar";
                            echo $this->html_helper->close_tag('a');
                            
                         echo $this->html_helper->close_tag('td',array("class"=>"tr_class"));
                         
                         echo $this->html_helper->open_tag('td',array("class"=>"tr_class"));
                           
                           echo $this->html_helper->open_tag('a',array("href"=>BASE_URL . "citas/delete_specialty/".$value["id"].".html"));
                            echo "Eliminar";
                           echo $this->html_helper->close_tag('a'); 
                            
                         echo $this->html_helper->close_tag('td',array("class"=>"tr_class"));
                         
                      echo $this->html_helper->close_tag('tr');
                    
                    
                ?>    
                    
                
                <?php
                    endforeach;
                endif; 
                echo $this->html_helper->close_tag('tbody');
                
                echo $this->html_helper->close_tag('table');
                
                ?>
                <div id="controls">
            		<div id="perpage">
            			<select onchange="sorter.size(this.value)">
            			<option value="5" >5</option>
            				<option value="10" selected="selected">10</option>
            				<option value="20">20</option>
            				<option value="50">50</option>
            				<option value="100">100</option>
            			</select>
            			<span>Registros Por Pagina</span>
            		</div>
            		<div id="navigation">
            			<img src="<?php echo $_layoutParams['ruta_img']; ?>first.gif" width="16" height="16" alt="First Page" onclick="sorter.move(-1,true)" />
            			<img src="<?php echo $_layoutParams['ruta_img']; ?>previous.gif" width="16" height="16" alt="First Page" onclick="sorter.move(-1)" />
            			<img src="<?php echo $_layoutParams['ruta_img']; ?>next.gif" width="16" height="16" alt="First Page" onclick="sorter.move(1)" />
            			<img src="<?php echo $_layoutParams['ruta_img']; ?>last.gif" width="16" height="16" alt="Last Page" onclick="sorter.move(1,true)" />
            		</div>
            		<div id="text">Vista Pagina <span id="currentpage"></span> de <span id="pagelimit"></span></div>
            	</div>
            	<script src="<?php echo $_layoutParams['ruta_js']; ?>script_table_sorter.js" type="text/javascript"></script>
            	<script type="text/javascript">
              var sorter = new TINY.table.sorter("sorter");
            	sorter.head = "head";
            	sorter.asc = "asc";
            	sorter.desc = "desc";
            	sorter.even = "evenrow";
            	sorter.odd = "oddrow";
            	sorter.evensel = "evenselected";
            	sorter.oddsel = "oddselected";
            	sorter.paginate = true;
            	sorter.currentid = "currentpage";
            	sorter.limitid = "pagelimit";
            	sorter.init("table",1);
              </script>
                <?php
                echo $this->html_helper->close_tag("center");
                ?>            
                    
            </section>