  <section id="content_in">
    <h3 style="color: #ba1616;" class="msn_error">
                      <?php
                    
                    if(isset($this->messageError)){
                     ?>
                     <?php  
                     echo $this->messageError;
                     ?>
                     <?php   
                    }
                    
                    ?>
                    
                    <?php
                    
                    if(isset($this->messageOk)){
                     ?>
                     <?php  
                     echo $this->messageOk;
                     ?>
                     <?php   
                    }
                    
                    ?>
        </h3>
  
    <fieldset>
        
     <form action="" method="post" name="form_register" id="form_register">
        <legend></legend>
        <label>Identificacion:</label>
        <input type="text" name="usuario" value="<?php if(isset($_POST["valid"])) echo $_POST["usuario"]; ?>" />
       
        <label>Correo:</label>
        <input type="text" name="email" value="<?php if(isset($_POST["valid"])) echo $_POST["email"]; ?>" />
        <label>Tipo Usuario:</label>
        <select id="tipo_cita" name="tipo" >
            <option value="0">Seleccion un Tipo de Usuario</option>
            <option value="1">Admin</option>
            <option value="1">Medico</option>
            <option value="1">Paciente</option>
            
        </select>
        <label>Password</label>
        <input type="password" name="pass" />
        <label>Repetir Password</label>
        <input type="password" name="rpass" />
        <input type="hidden" name="valid" value="ok" />
        <div class="msn_resp"></div>
        <input type="button" title="Agregar Medico" value="Agregar Usuario" id="btn" onclick="javascript:validUser('<?php echo BASE_URL ?>','<?php echo DEFAULT_LAYOUT ?>');" />
        
        
        
     </form>   
    </fieldset>
  
  </section>