  <section id="content_in">
    
     <h3 style="color: #ba1616;" class="msn_error">
                      <?php
                    
                    if(isset($this->messageError)){
                     ?>
                     <?php  
                     echo $this->messageError;
                     ?>
                     <?php   
                    }
                    
                    ?>
        </h3>
  
    <fieldset>
       
     <form action="" method="post" name="form_remember" id="form_remember">
        <legend></legend>
        <label>Email:</label>
        <input type="text" name="email" value="" />
        <input type="hidden" name="valid" value="ok" />
        <input type="button" title="Recordar Datos" value="Recordar Datos" id="btn" onclick="javascript:$('#form_remember').submit();" />
        <label id="login"><a href="<?php echo BASE_URL . "users/login.html" ?>">Logueo</a></label>
        <label id="register"><a href="<?php echo BASE_URL . "users/register.html" ?>">Reg&iacute;strarme</a></label>
        
        
     </form>   
    </fieldset>
  
  </section>